version: 0.2
phases:
  build:
    commands:
      - echo "Building the application..."
post_build:
  commands:
    - aws s3 cp index.html s3://mahi-bucket-advdevops/index.html --content-type "text/html"
artifacts:
  files:
    - index.html
    - appspec.yml
    - scripts/**/*
  discard-paths: no
